var myFullpage = new fullpage('#content', {
	licenseKey: 'OPEN-SOURCE-GPLV3-LICENSE',
	menu: '#menu',
	lockAnchors: false,
	anchors:['homePage', 'aboutPage','quotesPage','teamPage','contactPage'],
	navigation: true,
	navigationPosition: 'right',
	navigationTooltips: ['Home', 'About','Quotes','Team','Contact'],
	showActiveTooltip: false,
	slidesNavigation: false,
	slidesNavPosition: 'bottom',
	//Scrolling
	css3: true,
	scrollingSpeed: 700,
	autoScrolling: true,
	fitToSection: true,
	fitToSectionDelay: 1000,
	scrollBar: false,
	loopBottom: false,
	loopTop: false,
	loopHorizontal: true,
	continuousVertical: false,
	continuousHorizontal: false,
	scrollHorizontally: false,
	interlockedSlides: false,
	dragAndMove: false,
	offsetSections: false,
	resetSliders: false,
	fadingEffect: false,
	scrollOverflow: true,
	scrollOverflowReset: false,
	scrollOverflowOptions: null,
	touchSensitivity: 15,
	normalScrollElementTouchThreshold: 5,
	bigSectionsDestination: null,
	//Accessibility
	keyboardScrolling: true,
	animateAnchor: true,
	recordHistory: true,
	//Design
	controlArrows: true,
	verticalCentered: true,
	paddingTop: '3.2em',
	paddingBottom: '50px',
	fixedElements: '.header, .footer',
	responsiveWidth: 0,
	responsiveHeight: 0,
	responsiveSlides: true,
	parallax: false,
	parallaxOptions: {type: 'reveal', percentage: 62, property: 'translate'},
	//Custom selectors
	sectionSelector: '.section',
	slideSelector: '.slide',
	lazyLoading: true
});
